// Generated by KARN agc v1.0 (JavaScript)
// DO NOT EDIT — edit the .kn source instead

class _Ok {
  constructor(v) { this.v = v; }
  toString() { return `Ok(${JSON.stringify(this.v)})`; }
}

class _Err extends Error {
  constructor(msg, ctx) { super(msg); this.ctx = ctx || []; }
  toString() { return `Err(${this.message})`; }
}

function _prop(v) {
  if (v instanceof _Err) throw v;
  if (v instanceof _Ok) return v.v;
  return v;
}

const http = {
  async get(url, opts) {
    try {
      const r = await fetch(url, opts);
      return new _Ok(await r.text());
    } catch(e) { return new _Err(e.message); }
  },
  async serve(port, routes) {
    console.log(`[karn:http] Serving on port ${port}`);
    return new _Ok(null);
  }
};

const fs = {
  read(path) {
    try { return new _Ok(require("fs").readFileSync(String(path), "utf8")); }
      catch(e) { return new _Err(e.message); }
  },
  write(path, content) {
    try { require("fs").writeFileSync(String(path), String(content)); return new _Ok(null); }
      catch(e) { return new _Err(e.message); }
  },
  list(path=".") {
    try { return new _Ok(require("fs").readdirSync(String(path))); }
      catch(e) { return new _Err(e.message); }
  }
};

const log = {
  info: (...a) => { const m = a.map(x => typeof x==="object" ? JSON.stringify(x) : String(x)).join(" "); console.log(`\x1b[36m[INFO]\x1b[0m ${m}`); return new _Ok(null); },
  warn: (...a) => { const m = a.map(x => typeof x==="object" ? JSON.stringify(x) : String(x)).join(" "); console.warn(`\x1b[33m[WARN]\x1b[0m ${m}`); return new _Ok(null); },
  err:  (...a) => { const m = a.map(x => typeof x==="object" ? JSON.stringify(x) : String(x)).join(" "); console.error(`\x1b[31m[ERR]\x1b[0m  ${m}`); return new _Ok(null); }
};

const env = {
  get: (k, d) => new _Ok(process.env[String(k)] ?? d ?? null),
  require: (k) => { const v = process.env[String(k)]; return v !== undefined ? new _Ok(v) : new _Err(`Required env var '${k}' not set`); }
};

const json = {
  parse: (s) => { try { return new _Ok(JSON.parse(String(s))); } catch(e) { return new _Err(e.message); } },
  stringify: (o, i) => { try { return new _Ok(JSON.stringify(o, null, i)); } catch(e) { return new _Err(e.message); } },
  pretty: (o) => { try { return new _Ok(JSON.stringify(o, null, 2)); } catch(e) { return new _Err(e.message); } }
};

const math = {
  abs: (x) => Math.abs(Number(x)), ceil: (x) => Math.ceil(Number(x)),
  floor: (x) => Math.floor(Number(x)), round: (x) => Math.round(Number(x)),
  sqrt: (x) => Math.sqrt(Number(x)), pow: (x, y) => Math.pow(Number(x), Number(y)),
  min: (...a) => Math.min(...a.map(Number)), max: (...a) => Math.max(...a.map(Number)),
  sin: (x) => Math.sin(Number(x)), cos: (x) => Math.cos(Number(x)),
  log: (x) => Math.log(Number(x)), pi: () => Math.PI, e: () => Math.E
};

const str = {
  join: (a, s="") => new _Ok(a.join(String(s))),
  split: (s, d=" ") => new _Ok(String(s).split(String(d))),
  replace: (s, o, n) => new _Ok(String(s).replace(String(o), String(n))),
  contains: (s, sub) => new _Ok(String(s).includes(String(sub))),
  starts: (s, p) => new _Ok(String(s).startsWith(String(p))),
  ends: (s, p) => new _Ok(String(s).endsWith(String(p))),
  trim: (s) => new _Ok(String(s).trim()),
  repeat: (s, n) => new _Ok(String(s).repeat(Number(n)))
};

const crypto = {
  uuid: () => new _Ok(crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2)),
};

const db = {
  q: (t, w) => { console.log(`[karn:db] Query: ${t} WHERE ${JSON.stringify(w)}`); return new _Ok([]); },
  exec: (sql, ...a) => { console.log(`[karn:db] Exec: ${sql} args=${JSON.stringify(a)}`); return new _Ok({rows_affected: 0}); }
};

const time = {
  now: () => new _Ok(Date.now() / 1000),
  sleep: (ms) => new Promise(r => setTimeout(() => r(new _Ok(null)), Number(ms))),
  fmt: (ts, f) => new _Ok(new Date((ts || Date.now()/1000) * 1000).toISOString()),
  date: () => { const d = new Date(); return new _Ok({year: d.getFullYear(), month: d.getMonth()+1, day: d.getDate()}); }
};

function print(...args) { console.log(...args.map(String)); return new _Ok(null); }
function len(x) { return x.length; }
function keys(x) { return Object.keys(x); }
function values(x) { return Object.values(x); }
function range(s, e) { const a=[]; for(let i=s; i<=(e||s); i++) a.push(i); return a; }
function type_of(x) { return typeof x; }
function sorted(x) { return [...x].sort(); }
function reversed(x) { return [...x].reverse(); }
function sum(x) { return x.reduce((a,b)=>a+b, 0); }
function any(x) { return x.some(Boolean); }
function all(x) { return x.every(Boolean); }


function fib(n) {
  return (() => { if (n === 0) { return 0 }; if (n === 1) { return 1 }; { const x = n; return (fib((x - 1)) + fib((x - 2))) } return null; })();
}

console.log(fib(10));