/* Generated by KARN agc v1.0 (C) */
/* DO NOT EDIT — edit the .kn source instead */

/* KARN C Runtime — v1.0 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
#include <errno.h>

/* ── Value system ── */
typedef enum { VAL_NIL, VAL_NUM, VAL_STR, VAL_BOOL, VAL_OK, VAL_ERR, VAL_ARR, VAL_MAP } ValType;

typedef struct Val Val;
typedef struct Arr  Arr;
typedef struct Map  Map;

struct Arr  { int len; int cap; Val* items; };
struct Map  { int len; int cap; Val* keys; Val* vals; };

struct Val {
    ValType type;
    union {
        double  num;
        char*   str;
        bool    b;
        Val*    ok_val;
        char*   err_msg;
        Arr*    arr;
        Map*    map;
    } as;
};

Val val_nil(void)    { Val v = {VAL_NIL, {0}}; return v; }
Val val_num(double n){ Val v = {VAL_NUM, {.num=n}}; return v; }
Val val_bool(bool b) { Val v = {VAL_BOOL, {.b=b}}; return v; }
Val val_str(const char* s){
    Val v = {VAL_STR, {.str=strdup(s?s:"")}}; return v;
}
Val val_ok(Val v)   {
    Val r = {VAL_OK, {.ok_val=malloc(sizeof(Val))}}; *r.as.ok_val=v; return r;
}
Val val_err(const char* m){ Val v={VAL_ERR,{.err_msg=strdup(m?m:"")}}; return v; }

Arr* arr_new(int cap){
    Arr* a = malloc(sizeof(Arr)); a->len=0; a->cap=cap;
    a->items = malloc(sizeof(Val)*cap); return a;
}
Val val_arr(Arr* a){ Val v={VAL_ARR,{.arr=a}}; return v; }

Map* map_new(int cap){
    Map* m = malloc(sizeof(Map)); m->len=0; m->cap=cap;
    m->keys = malloc(sizeof(Val)*cap); m->vals = malloc(sizeof(Val)*cap); return m;
}
Val val_map(Map* m){ Val v={VAL_MAP,{.map=m}}; return v; }

void arr_push(Arr* a, Val v){
    if(a->len >= a->cap){ a->cap*=2; a->items=realloc(a->items,sizeof(Val)*a->cap); }
    a->items[a->len++] = v;
}

void map_put(Map* m, Val k, Val v){
    for(int i=0;i<m->len;i++){
        if(k.type==VAL_NUM && m->keys[i].type==VAL_NUM && m->keys[i].as.num==k.as.num){ m->vals[i]=v; return; }
        if(k.type==VAL_STR && m->keys[i].type==VAL_STR && strcmp(m->keys[i].as.str,k.as.str)==0){ m->vals[i]=v; return; }
    }
    if(m->len >= m->cap){ m->cap*=2; m->keys=realloc(m->keys,sizeof(Val)*m->cap); m->vals=realloc(m->vals,sizeof(Val)*m->cap); }
    m->keys[m->len]=k; m->vals[m->len]=v; m->len++;
}

Val map_get(Map* m, Val k){
    for(int i=0;i<m->len;i++){
        if(k.type==VAL_NUM && m->keys[i].type==VAL_NUM && m->keys[i].as.num==k.as.num) return m->vals[i];
        if(k.type==VAL_STR && m->keys[i].type==VAL_STR && strcmp(m->keys[i].as.str,k.as.str)==0) return m->vals[i];
    }
    return val_nil();
}

/* ── Printing ── */
void val_print(Val v){
    switch(v.type){
        case VAL_NIL:  printf("nil"); break;
        case VAL_NUM:  printf("%g", v.as.num); break;
        case VAL_STR:  printf("%s", v.as.str); break;
        case VAL_BOOL: printf("%s", v.as.b?"true":"false"); break;
        case VAL_OK:   printf("Ok("); val_print(*v.as.ok_val); printf(")"); break;
        case VAL_ERR:  printf("Err(%s)", v.as.err_msg); break;
        case VAL_ARR:  printf("["); for(int i=0;i<v.as.arr->len;i++){ if(i) printf(", "); val_print(v.as.arr->items[i]); } printf("]"); break;
        case VAL_MAP:  printf("{"); for(int i=0;i<v.as.map->len;i++){ if(i) printf(", "); val_print(v.as.map->keys[i]); printf(": "); val_print(v.as.map->vals[i]); } printf("}"); break;
    }
}
void val_println(Val v){ val_print(v); printf("\n"); }

/* ── Conversions ── */
double _val_to_num(Val v){ if(v.type==VAL_NUM) return v.as.num; return 0; }
const char* _val_to_str(Val v){
    static char buf[256];
    if(v.type==VAL_STR) return v.as.str;
    if(v.type==VAL_NUM){ snprintf(buf,sizeof(buf),"%g",v.as.num); return buf; }
    if(v.type==VAL_BOOL){ return v.as.b?"true":"false"; }
    return "nil";
}

/* ── Error propagation ── */
Val _prop(Val v){
    if(v.type==VAL_ERR){ val_println(v); exit(1); }
    if(v.type==VAL_OK) return *v.as.ok_val;
    return v;
}

/* ── Built-in functions ── */
Val karn_len(Val v){
    if(v.type==VAL_ARR) return val_num(v.as.arr->len);
    if(v.type==VAL_STR) return val_num(strlen(v.as.str));
    return val_num(0);
}

Val karn_range(Val s, Val e){
    int start=(int)_val_to_num(s), end=(int)_val_to_num(e);
    Arr* a = arr_new(end-start+1);
    for(int i=start;i<=end;i++) arr_push(a, val_num(i));
    return val_arr(a);
}

Val karn_sum(Val v){
    double sum=0; if(v.type==VAL_ARR){ for(int i=0;i<v.as.arr->len;i++) sum+=_val_to_num(v.as.arr->items[i]); }
    return val_num(sum);
}

Val karn_sorted(Val v){
    if(v.type!=VAL_ARR) return v;
    Arr* a=v.as.arr; Arr* b=arr_new(a->len);
    for(int i=0;i<a->len;i++) b->items[i]=a->items[i]; b->len=a->len;
    for(int i=0;i<b->len-1;i++) for(int j=i+1;j<b->len;j++){
        if(_val_to_num(b->items[i])>_val_to_num(b->items[j])){ Val t=b->items[i]; b->items[i]=b->items[j]; b->items[j]=t; }
    }
    return val_arr(b);
}

Val karn_reversed(Val v){
    if(v.type!=VAL_ARR) return v;
    Arr* a=v.as.arr; Arr* b=arr_new(a->len);
    for(int i=0;i<a->len;i++) b->items[i]=a->items[a->len-1-i]; b->len=a->len;
    return val_arr(b);
}

Val karn_any(Val v){
    if(v.type!=VAL_ARR) return val_bool(false);
    for(int i=0;i<v.as.arr->len;i++) if(_val_to_num(v.as.arr->items[i])) return val_bool(true);
    return val_bool(false);
}

Val karn_all(Val v){
    if(v.type!=VAL_ARR) return val_bool(false);
    for(int i=0;i<v.as.arr->len;i++) if(!_val_to_num(v.as.arr->items[i])) return val_bool(false);
    return val_bool(true);
}

/* ── String methods ── */
Val str_upper(Val v){
    if(v.type!=VAL_STR) return v;
    char* s=strdup(v.as.str); for(int i=0;s[i];i++) if(s[i]>='a'&&s[i]<='z') s[i]-=32;
    Val r=val_str(s); free(s); return r;
}
Val str_lower(Val v){
    if(v.type!=VAL_STR) return v;
    char* s=strdup(v.as.str); for(int i=0;s[i];i++) if(s[i]>='A'&&s[i]<='Z') s[i]+=32;
    Val r=val_str(s); free(s); return r;
}
Val str_len(Val v){ return val_num(v.type==VAL_STR?strlen(v.as.str):0); }

/* ── Array methods ── */
Val arr_len(Val v){ return val_num(v.type==VAL_ARR?v.as.arr->len:0); }
Val arr_first(Val v){ return (v.type==VAL_ARR&&v.as.arr->len>0)?v.as.arr->items[0]:val_nil(); }
Val arr_last(Val v){ return (v.type==VAL_ARR&&v.as.arr->len>0)?v.as.arr->items[v.as.arr->len-1]:val_nil(); }

/* ── Math module ── */
Val math_abs(Val x){ return val_num(fabs(_val_to_num(x))); }
Val math_ceil(Val x){ return val_num(ceil(_val_to_num(x))); }
Val math_floor(Val x){ return val_num(floor(_val_to_num(x))); }
Val math_round(Val x){ return val_num(round(_val_to_num(x))); }
Val math_sqrt(Val x){ return val_num(sqrt(_val_to_num(x))); }
Val math_pow(Val x, Val y){ return val_num(pow(_val_to_num(x),_val_to_num(y))); }
Val math_min(Val x, Val y){ return val_num(fmin(_val_to_num(x),_val_to_num(y))); }
Val math_max(Val x, Val y){ return val_num(fmax(_val_to_num(x),_val_to_num(y))); }
Val math_sin(Val x){ return val_num(sin(_val_to_num(x))); }
Val math_cos(Val x){ return val_num(cos(_val_to_num(x))); }
Val math_log(Val x){ return val_num(log(_val_to_num(x))); }
Val math_pi(void){ return val_num(3.14159265358979); }
Val math_e(void){ return val_num(2.71828182845905); }

/* ── Time module ── */
Val time_now(void){ return val_num((double)time(NULL)); }
Val time_date(void){
    time_t t=time(NULL); struct tm* tm=localtime(&t);
    Map* m=map_new(3); map_put(m,val_str("year"),val_num(tm->tm_year+1900));
    map_put(m,val_str("month"),val_num(tm->tm_mon+1)); map_put(m,val_str("day"),val_num(tm->tm_mday));
    return val_map(m);
}

/* ── Env module ── */
Val env_get(Val k, Val d){
    const char* v=getenv(k.type==VAL_STR?k.as.str:"");
    return v?val_str(v):d;
}

/* ── Crypto module ── */
Val crypto_uuid(void){
    char buf[37]; snprintf(buf,sizeof(buf),"%08x-%04x-%04x-%04x-%012x",
        (unsigned)rand(),(unsigned)rand()%65536,(unsigned)rand()%65536,(unsigned)rand()%65536,(unsigned)rand());
    return val_str(buf);
}

/* ── JSON module ── */
Val json_stringify(Val v, Val indent){
    static char buf[4096];
    if(v.type==VAL_STR){ snprintf(buf,sizeof(buf),"\"%s\"",v.as.str); return val_str(buf); }
    if(v.type==VAL_NUM){ snprintf(buf,sizeof(buf),"%g",v.as.num); return val_str(buf); }
    if(v.type==VAL_BOOL){ return val_str(v.as.b?"true":"false"); }
    if(v.type==VAL_NIL){ return val_str("null"); }
    if(v.type==VAL_ARR){
        char tmp[4096]; int pos=0; pos+=snprintf(tmp+pos,sizeof(tmp)-pos,"[");
        for(int i=0;i<v.as.arr->len;i++){
            if(i) pos+=snprintf(tmp+pos,sizeof(tmp)-pos,", ");
            Val s=json_stringify(v.as.arr->items[i],indent);
            pos+=snprintf(tmp+pos,sizeof(tmp)-pos,"%s",s.as.str);
        }
        pos+=snprintf(tmp+pos,sizeof(tmp)-pos,"]");
        return val_str(tmp);
    }
    return val_str("{}");
}


int main(void) {
    srand(time(NULL));
    val_println(val_str("Hello from KARN!"));
    return 0;
}